# Generated by Django 3.0.2 on 2020-02-22 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Male_Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Male_Eyeglasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Male_Earring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Male_Cap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Female_Necklace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Female_Eyeglasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Female_Earring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Female_Cap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('stock', models.IntegerField()),
                ('script', models.CharField(default='asd', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pic')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
