# Generated by Django 3.0.2 on 2020-02-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_directory',
            field=models.CharField(default='abcd', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='script',
            field=models.CharField(default='asd', max_length=100),
        ),
    ]
